In [2]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])
tscv = TimeSeriesSplit(n_splits=3)
print(tscv)
for train, test in tscv.split(X):
    print("%s %s" % (train, test))

TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None)
[0 1 2] [3]
[0 1 2 3] [4]
[0 1 2 3 4] [5]


In [14]:
z = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tscv = TimeSeriesSplit(n_splits=3, test_size=3, max_train_size=2)
for train, test in tscv.split(z):
    print(f"{train}, {test}")

[0], [1 2 3]
[2 3], [4 5 6]
[5 6], [7 8 9]
